### PR TITLE
feat: environment variables and dependencies validation

### LINKED ISSUE #58: Environment variable validation
Certain commands require additional access, and it would be nice to be able to detect if a command can be run before trying to run it. For example, if an expected environment variable isn't present, the command, when triggered, should error out for missing information. I'm thinking an array of strings representing the expected environment variables (like this but in golang https://github.com/mathew-fleisch/tools/blob/main/scripts/check-environment-variables.sh) at runtime. Just after a valid command is identified, and before it is executed, iterate through the expected environment variables to ensure they are not null/empty. Because there is no validation currently, this is a bug, and a potential enhancement.

### PR DESCRIPTION
**Pull request by wisdommatt**
@mathew-fleisch  I have implemented environment variables and dependencies validation before processing a valid command, i would like you to review this PR before i will go ahead to update the examples

Fix #58

### CODE REVIEW

**Comment by mathew-fleisch** [comment]
hey @wisdommatt! Nicely Done! This is exactly what I was hoping for! I tested it out and worked perfectly. Please go ahead and update the examples and any read-me information related to this change. Thanks!

Note: I made a stripped down dockerfile that intentionally had missing dependencies to test this functionality. It might be nice to add this dockerfile as Dockerfile.min. I will add a new issue for this idea with details from the changes I made to test your fork.

**Comment by wisdommatt** [comment]
@mathew-fleisch i will go ahead and update the examples and read-me 🚀

**Comment by wisdommatt** [comment]
@mathew-fleisch I just updated the examples and READMEs affected by this change

**Review by mathew-fleisch — APPROVED** [review]
Nicely done! Thanks!

**Comment by wisdommatt** [comment]
Thanks @mathew-fleisch , I will open a new PR for another issue shortly 👍🏿

**Pull request merged**
